# Generated by Django 5.2.1 on 2025-06-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allow_debt',
            field=models.BooleanField(default=False),
        ),
    ]
