# Generated by Django 5.2.1 on 2025-06-22 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_allow_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='debt_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='debt_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cleared', 'Cleared')], default='cleared', max_length=20),
        ),
    ]
