# Generated by Django 5.2.1 on 2025-05-22 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='alternative_suppliers',
            field=models.ManyToManyField(blank=True, related_name='alternative_materials', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='inventory.category'),
        ),
    ]
