# Generated by Django 5.2.1 on 2025-06-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='material',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='material',
            name='sku',
        ),
    ]
