# Generated by Django 5.2.1 on 2025-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('zaad', 'Zaad'), ('edahab', 'Edahab')], default='cash', max_length=20),
        ),
    ]
