# Generated by Django 5.2.1 on 2025-06-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for credit sales', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partially Paid')], default='paid', help_text='Payment status for credit sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('zaad', 'Zaad'), ('edahab', 'Edahab'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
    ]
