# Generated by Django 5.2.1 on 2025-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Expense category or type', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent', max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Optional details')),
                ('date', models.DateField(help_text='Date of the expense')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ['-date'],
            },
        ),
    ]
