# Generated by Django 5.2.1 on 2025-05-22 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_info', to='inventory.material'),
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_info', to='suppliers.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliermaterial',
            unique_together={('supplier', 'material')},
        ),
    ]
