# Generated by Django 5.2.1 on 2025-06-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='state',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='website',
        ),
    ]
